# 应用名称
spring:
  application:
    name: springcloud-demo-service
  # EurekaServer地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
  instance:
    prefer-ip-address: true
    # 指定自己的ip信息，不指定的话会自己寻找
    ip-address: 127.0.0.1


